menu:
  首页: /
  目录: /archives/
  #About: /about/
  #Subscribe: /atom.xml
weibo:
    name:
    uid:
    link:

widgets: 
- menu
- weibo
- category
- tagcloud

excerpt_link: 阅读更多

fancybox: true

# 友言评论
UYUserId:

# cnzz统计
cnzzId:

# JiaThis分享
jiathisUUID:


rss: http://xxx.xx/atom.xml